#!/bin/bash

# USAGE: $ fon 

USER_NAME='username@belgacomfon.be'
PASSWORD='password'

# COPY username & password
echo "$USER_NAME $PASSWORD" | pbcopy
printf '\033[1;96mCredentials copied!\n\033[0m'

# GET cookie
printf '\033[1;33mGetting cookie'
curl -c .fonCookie -o /dev/null http://www.google.be 2> /dev/null
printf ' \033[1;92mOK\n\033[0m'

# POST login credentials
printf '\033[1;33mTry to reconnect\033[0m'
curl -Lb .fonCookie -d "login[user]=$USER_NAME&login[pass]=$PASSWORD" "https://belgacom.portal.fon.com/login/processLogin" 2>/dev/null -o /dev/null
printf ' \033[1;92mOK\n\033[0m'

# remove cookie
rm .fonCookie 2>/dev/null

