#!/bin/bash

# USAGE: $ fon 

USER_NAME='username@belgacomfon.be'
PASSWORD='password'

# COPY username & password
echo "$USER_NAME $PASSWORD" | pbcopy
echo "Credentials copied!"


# TRY auto connect
# GET cookie
curl -c .fonCookie -o /dev/null -L http://google.com
# POST login credentials
echo "Try Reconneting..."
curl -Lb .fonCookie -d "login[user]=$USER_NAME&login[pass]=$PASSWORD" "https://belgacom.portal.fon.com/login/processLogin" 2>/dev/null -o /dev/null
# remove cookie
rm .fonCookie

